class APPLICATION

create make

feature

	make
			-- Don't change the body of `make'. Because the placeholders will be replaced by other programs.
		local
--			q: TWO_WAY_TREE [INTEGER]
--			s: TWO_WAY_SORTED_SET [STRING]
--			t: DS_LINKED_STACK [ANY]
--			u: DS_LINKED_LIST [ANY]
--			v: DS_HASH_SET [STRING]
--			w: ARRAYED_SET [ANY]
--			x: BOUNDED_QUEUE [ANY]
--			y: LINKED_SET [ANY]
--			z: DS_ARRAYED_LIST [ANY]
--			test: TC__INT_SORTED_SET__remove__CMD__F__c6__b4__REC_V_SORTED_SET_ITERATOR__search__TAG_before_definition__1512076340__1482164537
		do
--			create test
--			test.generated_test_1
		end

	a1: MML_BAG [ANY]
	a2: MML_INTERVAL
	a3: MML_MAP [ANY, ANY]
	a4: MML_MODEL
	a5: MML_RELATION [ANY, ANY]
	a6: MML_SEQUENCE [ANY]
	a7: MML_SET [ANY]

	a8: V_BINARY_TREE_CELL [ANY]
	a9: V_CELL [ANY]
	a10: V_LINKABLE [ANY]
	a11: V_ARRAY [ANY]
	a12: V_BINARY_TREE [ANY]
	a13: V_CONTAINER [ANY]
	a14: V_SEQUENCE [ANY]
	a15: V_DISPENSER [ANY]
	a16: V_LINKED_QUEUE [ANY]
	a17: V_LINKED_STACK [ANY]
	a18: V_QUEUE [ANY]
	a19: V_STACK [ANY]
	a20: V_ARRAYED_LIST_ITERATOR [ANY]
	a21: V_BINARY_TREE_CURSOR [ANY]
	a22: V_BINARY_TREE_ITERATOR [ANY]
	a23: V_CELL_CURSOR [ANY]
	a24: V_HASH_SET_ITERATOR [ANY]
	a25: V_INDEX_ITERATOR [ANY]
	a26: V_INORDER_ITERATOR [ANY]
	a27: V_INPUT_ITERATOR [ANY]
	a28: V_ITERATOR [ANY]
	a29: V_LINKED_LIST_ITERATOR [ANY]
	a30: V_LIST_ITERATOR [ANY]
	a31: V_POSTORDER_ITERATOR [ANY]
	a32: V_PREORDER_ITERATOR [ANY]
	a33: V_PROXY_ITERATOR [ANY]
	a34: V_SEQUENCE_ITERATOR [ANY]
	a35: V_SET_ITERATOR [ANY]
	a36: V_SET_TABLE_ITERATOR [ANY, ANY]
	a37: V_SORTED_SET_ITERATOR [ANY]
	a38: V_TABLE_ITERATOR [ANY, ANY]
	a39: V_ARRAYED_LIST [ANY]
	a40: V_LINKED_LIST [ANY]
	a41: V_LIST [ANY]
	a42: V_MAP [ANY, ANY]
	a43: V_UPDATABLE_MAP [ANY, ANY]
	a44: V_GENERAL_HASH_SET [ANY]
	a45: V_GENERAL_SORTED_SET [ANY]
	a46: V_HASH_SET [HASHABLE]
	a47: V_SET [ANY]
	a48: V_SORTED_SET [COMPARABLE]
	a49: V_CONSTANT_INPUT [ANY]
	a50: V_INPUT_STREAM [ANY]
	a51: V_OUTPUT_STREAM [ANY]
	a52: V_RANDOM
	a53: V_STANDARD_OUTPUT
	a54: V_STRING_INPUT [ANY]
	a55: V_STRING_OUTPUT
	a56: V_GENERAL_HASH_TABLE [ANY, ANY]
	a57: V_GENERAL_SORTED_TABLE [ANY, ANY]
	a58: V_HASH_TABLE [HASHABLE, ANY]
	a59: V_SET_TABLE [ANY, ANY]
	a60: V_SORTED_TABLE [COMPARABLE, ANY]
	a61: V_TABLE [ANY, ANY]
	a62: V_EQUALITY [ANY]
	a63: V_HASH [HASHABLE]
	a64: V_ORDER [COMPARABLE]
	a65: INT_HASH_SET
	a66: STRING_HASH_SET
	a67: INT_SORTED_SET
	a68: STRING_SORTED_SET
	a69: INT_HASH_TABLE
	a70: STRING_HASH_TABLE
	a71: INT_SORTED_TABLE
	a72: STRING_SORTED_TABLE
end
